### PR TITLE
Added .ps, .psd and .ai files to the repo

### PR DESCRIPTION
**Pull request by ShubhayuB**
I have added 3 Files:
"sample.ai"
"sample.ps"
"sample.psd"

All the three contain some sample data. 

I would be happy to contribute more, if you would want.
Thank You!

### CODE REVIEW

**Comment by sunn-e** [comment]
Hey @ShubhayuB , is there any way I can watch/test/render this files without having to download anything?

**Comment by ShubhayuB** [comment]
Try using online softwares which can edit these files.
You can google and you will find

(Also this project is not showing as a part of the Hacktoberfest. Can you make the necessary changes?)

**Comment by sunn-e** [comment]
> (Also this project is not showing as a part of the Hacktoberfest. Can you make the necessary changes?)
#9

**Comment by ShubhayuB** [comment]
I meant this @sunn-e
Screenshot 2021-10-18 215659

**Pull request merged**
